### ISSUE TITLE
Action Buttons on Consult Form

### ISSUE THREAD

**Issue by jeansmit** [first-care-solutions/ed-greenline#6]
Add the following action buttons at the bottom of the Consult Form in the Landing Page

### Button 1: Reset Form
When this button is clicked, the following events should follow:
- Display an Ionic Popup with two buttons, namely 'Yes' and 'Cancel'. The popup must display the following message: "Are you sure you wish to clear the information on the form?"
- When the user clicks "Yes" on the popup described above, all the form input values must be reset to their default state
- When the user clicks on "Cancel" on the popup described above, close the popup and leave the values on the form as is

### Button 2: Save and Connect
When this button is clicked the following event needs to take place:
Make an HTTP request to the API and submit the Consult Form information (See HTTP Details below)
If the http response result is false, show a popup with the following message: "Unfortunately we are not able to connect with the Telemedicine doctor at this time. Please try again later."
If the HTTP response result is true, navigate the user to the Virtual Consult Page

**HTTP Details**
Type: POST
URL: https://care-first.co.za/api/booking
The JSON object created in the ConsultForm on the Landing Page must be submitted in the POST body

**HTTP Response**
```
{
  result: boolean
  data: any
  message: string (optional)
}
```

**Comment by jakesfcoetz** [comment]
Done by Mogale
